/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const FareStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'counterProposed' : IDL.Null,
});
export const RideRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'passenger' : IDL.Principal,
  'completionTime' : IDL.Opt(Time),
  'dropoffLocation' : IDL.Text,
  'counterFare' : IDL.Opt(IDL.Nat),
  'proposedFare' : IDL.Nat,
  'timestamp' : Time,
  'fareStatus' : FareStatus,
  'driver' : IDL.Opt(IDL.Principal),
  'pickupLocation' : IDL.Text,
});
export const Location = IDL.Record({
  'latitude' : IDL.Text,
  'longitude' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'ratingCount' : IDL.Nat,
  'isDriver' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'rating' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Opt(Location),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptCounterFare' : IDL.Func([IDL.Nat], [], []),
  'acceptRide' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelRide' : IDL.Func([IDL.Nat], [], []),
  'completeTrip' : IDL.Func([IDL.Nat], [], []),
  'createRideRequest' : IDL.Func([RideRequest], [IDL.Nat], []),
  'getActiveRideForUser' : IDL.Func([], [IDL.Opt(RideRequest)], []),
  'getActiveRides' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
  'getAllTrips' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
  'getAvailableDrivers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBestRatedDrivers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriverTrips' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(RideRequest)],
      ['query'],
    ),
  'getPendingTrips' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
  'getProfileByPhone' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'getRiders' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'proposeCounterFare' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'rateDriver' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startTrip' : IDL.Func([IDL.Nat], [], []),
  'switchRole' : IDL.Func([], [UserProfile], []),
  'updateLocation' : IDL.Func([Location], [], []),
  'updateProfileName' : IDL.Func([IDL.Text], [], []),
  'updateProfilePhone' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const FareStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'counterProposed' : IDL.Null,
  });
  const RideRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'passenger' : IDL.Principal,
    'completionTime' : IDL.Opt(Time),
    'dropoffLocation' : IDL.Text,
    'counterFare' : IDL.Opt(IDL.Nat),
    'proposedFare' : IDL.Nat,
    'timestamp' : Time,
    'fareStatus' : FareStatus,
    'driver' : IDL.Opt(IDL.Principal),
    'pickupLocation' : IDL.Text,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Text,
    'longitude' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'ratingCount' : IDL.Nat,
    'isDriver' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'rating' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Opt(Location),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptCounterFare' : IDL.Func([IDL.Nat], [], []),
    'acceptRide' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelRide' : IDL.Func([IDL.Nat], [], []),
    'completeTrip' : IDL.Func([IDL.Nat], [], []),
    'createRideRequest' : IDL.Func([RideRequest], [IDL.Nat], []),
    'getActiveRideForUser' : IDL.Func([], [IDL.Opt(RideRequest)], []),
    'getActiveRides' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
    'getAllTrips' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
    'getAvailableDrivers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBestRatedDrivers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriverTrips' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(RideRequest)],
        ['query'],
      ),
    'getPendingTrips' : IDL.Func([], [IDL.Vec(RideRequest)], ['query']),
    'getProfileByPhone' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'getRiders' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'proposeCounterFare' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'rateDriver' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startTrip' : IDL.Func([IDL.Nat], [], []),
    'switchRole' : IDL.Func([], [UserProfile], []),
    'updateLocation' : IDL.Func([Location], [], []),
    'updateProfileName' : IDL.Func([IDL.Text], [], []),
    'updateProfilePhone' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };