/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FareStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'counterProposed' : null };
export interface Location { 'latitude' : string, 'longitude' : string }
export interface RideRequest {
  'id' : bigint,
  'status' : Status,
  'passenger' : Principal,
  'completionTime' : [] | [Time],
  'dropoffLocation' : string,
  'counterFare' : [] | [bigint],
  'proposedFare' : bigint,
  'timestamp' : Time,
  'fareStatus' : FareStatus,
  'driver' : [] | [Principal],
  'pickupLocation' : string,
}
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile {
  'ratingCount' : bigint,
  'isDriver' : boolean,
  'name' : string,
  'createdAt' : Time,
  'rating' : bigint,
  'phoneNumber' : string,
  'location' : [] | [Location],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptCounterFare' : ActorMethod<[bigint], undefined>,
  'acceptRide' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelRide' : ActorMethod<[bigint], undefined>,
  'completeTrip' : ActorMethod<[bigint], undefined>,
  'createRideRequest' : ActorMethod<[RideRequest], bigint>,
  'getActiveRideForUser' : ActorMethod<[], [] | [RideRequest]>,
  'getActiveRides' : ActorMethod<[], Array<RideRequest>>,
  'getAllTrips' : ActorMethod<[], Array<RideRequest>>,
  'getAvailableDrivers' : ActorMethod<[], Array<UserProfile>>,
  'getBestRatedDrivers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDriverTrips' : ActorMethod<[Principal], Array<RideRequest>>,
  'getPendingTrips' : ActorMethod<[], Array<RideRequest>>,
  'getProfileByPhone' : ActorMethod<[string], UserProfile>,
  'getRiders' : ActorMethod<[], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<UserProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'proposeCounterFare' : ActorMethod<[bigint, bigint], undefined>,
  'rateDriver' : ActorMethod<[Principal, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startTrip' : ActorMethod<[bigint], undefined>,
  'switchRole' : ActorMethod<[], UserProfile>,
  'updateLocation' : ActorMethod<[Location], undefined>,
  'updateProfileName' : ActorMethod<[string], undefined>,
  'updateProfilePhone' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];