/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: string;
    longitude: string;
}
export type Time = bigint;
export interface RideRequest {
    id: bigint;
    status: Status;
    passenger: Principal;
    completionTime?: Time;
    dropoffLocation: string;
    counterFare?: bigint;
    proposedFare: bigint;
    timestamp: Time;
    fareStatus: FareStatus;
    driver?: Principal;
    pickupLocation: string;
}
export interface UserProfile {
    ratingCount: bigint;
    isDriver: boolean;
    name: string;
    createdAt: Time;
    rating: bigint;
    phoneNumber: string;
    location?: Location;
}
export enum FareStatus {
    pending = "pending",
    accepted = "accepted",
    counterProposed = "counterProposed"
}
export enum Status {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    accepted = "accepted",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptCounterFare(rideId: bigint): Promise<void>;
    acceptRide(rideId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelRide(rideId: bigint): Promise<void>;
    completeTrip(rideId: bigint): Promise<void>;
    createRideRequest(ride: RideRequest): Promise<bigint>;
    getActiveRideForUser(): Promise<RideRequest | null>;
    getActiveRides(): Promise<Array<RideRequest>>;
    getAllTrips(): Promise<Array<RideRequest>>;
    getAvailableDrivers(): Promise<Array<UserProfile>>;
    getBestRatedDrivers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDriverTrips(driver: Principal): Promise<Array<RideRequest>>;
    getPendingTrips(): Promise<Array<RideRequest>>;
    getProfileByPhone(phoneNumber: string): Promise<UserProfile>;
    getRiders(): Promise<Array<UserProfile>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsers(): Promise<Array<UserProfile>>;
    isCallerAdmin(): Promise<boolean>;
    proposeCounterFare(rideId: bigint, counterFare: bigint): Promise<void>;
    rateDriver(driver: Principal, rating: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startTrip(rideId: bigint): Promise<void>;
    switchRole(): Promise<UserProfile>;
    updateLocation(location: Location): Promise<void>;
    updateProfileName(name: string): Promise<void>;
    updateProfilePhone(phoneNumber: string): Promise<void>;
}
import type { FareStatus as _FareStatus, Location as _Location, RideRequest as _RideRequest, Status as _Status, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptCounterFare(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptCounterFare(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptCounterFare(arg0);
            return result;
        }
    }
    async acceptRide(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptRide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptRide(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelRide(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelRide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelRide(arg0);
            return result;
        }
    }
    async completeTrip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTrip(arg0);
            return result;
        }
    }
    async createRideRequest(arg0: RideRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRideRequest(to_candid_RideRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRideRequest(to_candid_RideRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getActiveRideForUser(): Promise<RideRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveRideForUser();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveRideForUser();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveRides(): Promise<Array<RideRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveRides();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveRides();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrips(): Promise<Array<RideRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrips();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrips();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableDrivers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableDrivers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableDrivers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBestRatedDrivers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBestRatedDrivers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBestRatedDrivers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverTrips(arg0: Principal): Promise<Array<RideRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverTrips(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverTrips(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingTrips(): Promise<Array<RideRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingTrips();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingTrips();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileByPhone(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByPhone(arg0);
                return from_candid_UserProfile_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByPhone(arg0);
            return from_candid_UserProfile_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiders(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiders();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiders();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async proposeCounterFare(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.proposeCounterFare(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.proposeCounterFare(arg0, arg1);
            return result;
        }
    }
    async rateDriver(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateDriver(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateDriver(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startTrip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTrip(arg0);
            return result;
        }
    }
    async switchRole(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.switchRole();
                return from_candid_UserProfile_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.switchRole();
            return from_candid_UserProfile_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLocation(arg0: Location): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocation(arg0);
            return result;
        }
    }
    async updateProfileName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileName(arg0);
            return result;
        }
    }
    async updateProfilePhone(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePhone(arg0);
            return result;
        }
    }
}
function from_candid_FareStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FareStatus): FareStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_RideRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideRequest): RideRequest {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RideRequest]): RideRequest | null {
    return value.length === 0 ? null : from_candid_RideRequest_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    passenger: Principal;
    completionTime: [] | [_Time];
    dropoffLocation: string;
    counterFare: [] | [bigint];
    proposedFare: bigint;
    timestamp: _Time;
    fareStatus: _FareStatus;
    driver: [] | [Principal];
    pickupLocation: string;
}): {
    id: bigint;
    status: Status;
    passenger: Principal;
    completionTime?: Time;
    dropoffLocation: string;
    counterFare?: bigint;
    proposedFare: bigint;
    timestamp: Time;
    fareStatus: FareStatus;
    driver?: Principal;
    pickupLocation: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n12(_uploadFile, _downloadFile, value.status),
        passenger: value.passenger,
        completionTime: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.completionTime)),
        dropoffLocation: value.dropoffLocation,
        counterFare: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.counterFare)),
        proposedFare: value.proposedFare,
        timestamp: value.timestamp,
        fareStatus: from_candid_FareStatus_n16(_uploadFile, _downloadFile, value.fareStatus),
        driver: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.driver)),
        pickupLocation: value.pickupLocation
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ratingCount: bigint;
    isDriver: boolean;
    name: string;
    createdAt: _Time;
    rating: bigint;
    phoneNumber: string;
    location: [] | [_Location];
}): {
    ratingCount: bigint;
    isDriver: boolean;
    name: string;
    createdAt: Time;
    rating: bigint;
    phoneNumber: string;
    location?: Location;
} {
    return {
        ratingCount: value.ratingCount,
        isDriver: value.isDriver,
        name: value.name,
        createdAt: value.createdAt,
        rating: value.rating,
        phoneNumber: value.phoneNumber,
        location: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
}): Status {
    return "cancelled" in value ? Status.cancelled : "pending" in value ? Status.pending : "completed" in value ? Status.completed : "accepted" in value ? Status.accepted : "inProgress" in value ? Status.inProgress : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    counterProposed: null;
}): FareStatus {
    return "pending" in value ? FareStatus.pending : "accepted" in value ? FareStatus.accepted : "counterProposed" in value ? FareStatus.counterProposed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RideRequest>): Array<RideRequest> {
    return value.map((x)=>from_candid_RideRequest_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n21(_uploadFile, _downloadFile, x));
}
function to_candid_FareStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FareStatus): _FareStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_RideRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RideRequest): _RideRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ratingCount: bigint;
    isDriver: boolean;
    name: string;
    createdAt: Time;
    rating: bigint;
    phoneNumber: string;
    location?: Location;
}): {
    ratingCount: bigint;
    isDriver: boolean;
    name: string;
    createdAt: _Time;
    rating: bigint;
    phoneNumber: string;
    location: [] | [_Location];
} {
    return {
        ratingCount: value.ratingCount,
        isDriver: value.isDriver,
        name: value.name,
        createdAt: value.createdAt,
        rating: value.rating,
        phoneNumber: value.phoneNumber,
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Status;
    passenger: Principal;
    completionTime?: Time;
    dropoffLocation: string;
    counterFare?: bigint;
    proposedFare: bigint;
    timestamp: Time;
    fareStatus: FareStatus;
    driver?: Principal;
    pickupLocation: string;
}): {
    id: bigint;
    status: _Status;
    passenger: Principal;
    completionTime: [] | [_Time];
    dropoffLocation: string;
    counterFare: [] | [bigint];
    proposedFare: bigint;
    timestamp: _Time;
    fareStatus: _FareStatus;
    driver: [] | [Principal];
    pickupLocation: string;
} {
    return {
        id: value.id,
        status: to_candid_Status_n5(_uploadFile, _downloadFile, value.status),
        passenger: value.passenger,
        completionTime: value.completionTime ? candid_some(value.completionTime) : candid_none(),
        dropoffLocation: value.dropoffLocation,
        counterFare: value.counterFare ? candid_some(value.counterFare) : candid_none(),
        proposedFare: value.proposedFare,
        timestamp: value.timestamp,
        fareStatus: to_candid_FareStatus_n7(_uploadFile, _downloadFile, value.fareStatus),
        driver: value.driver ? candid_some(value.driver) : candid_none(),
        pickupLocation: value.pickupLocation
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} {
    return value == Status.cancelled ? {
        cancelled: null
    } : value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.accepted ? {
        accepted: null
    } : value == Status.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FareStatus): {
    pending: null;
} | {
    accepted: null;
} | {
    counterProposed: null;
} {
    return value == FareStatus.pending ? {
        pending: null
    } : value == FareStatus.accepted ? {
        accepted: null
    } : value == FareStatus.counterProposed ? {
        counterProposed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
